swagger: '2.0'
info:
  title: Example API for db dependency injection
  version: "1.0"
consumes:
  - application/json
produces:
  - application/json
basePath: /v1.0
paths:
  /result:
    get:
      operationId: api.operations.get_data
      summary: Get data
      responses:
        '200':
          description: "Return response success failure"
          schema:
            type: string
            items:
              $ref: '#/definitions/Item'
  /store_user:
    post:
      operationId: api.operations.store_user
      summary: Post data
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          description: User object that needs to be added.
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Return response success failure
          schema:
            type: string
            items:
              $ref: '#/definitions/User'

definitions:
  Item:
    type: object
    properties:
      id:
        type: string
        description: Unique identifier
        example: "test"
        readOnly: true
      name:
        type: string
  User:
    type: object
    properties:
      # id:
      #   type: string
      #   description: Unique identifier
      #   readOnly: true
      name:
        type: string
      contact:
        type: string
      email:
        type: string
        
