swagger: "2.0"

info:
  title: "My first API"
  version: "1.0"

basePath: /v1.0

paths:
  /items/:
    get:
      responses:
        '200':
          description: 'Fetch a list of items'
          schema:
            type: array
            items:
              $ref: '#/definitions/Item'
    post:
      summary:  users
      parameters:
        - name: user
          in: body
          schema:
            $ref: '#/definitions/User'
      responses:
        200:
          description: User created



definitions:
  Item:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name: { type: string }
  User:
    type: object
    required:
      - name
      - id
    properties:
      id:
        type: integer
        description: Unique identifier
        example: 123
      name:
        type: string
        description: User's name
        example: "Susie"
