swagger: "2.0"

info:
  title: "My first API"
  version: "1.0"

basePath: /v1.0

paths:
  /items/:
    get:
      operationId: app.search
      responses:
        '200':
          description: 'Fetch a list of items'

